### ISSUE TITLE
v1.6.0 is not published

### ISSUE THREAD

**Issue by htanjo** [shakyShane/grunt-browser-sync#90]
This repository contains v1.6.0 release, but [grunt-browser-sync in npm](https://www.npmjs.com/package/grunt-browser-sync) is still 1.5.3.
Is there any problem? I'd like to use the new `keepalive` option.
Thanks.

**Comment by shakyShane** [comment]
This ensures you always get the latest version on BrowserSync, since grunt-browser-sync is just a wrapper

https://github.com/shakyShane/grunt-browser-sync/blob/master/package.json#L30

**Comment by htanjo** [comment]
Thanks for releasing 1.9.1. It works!
