### ISSUE TITLE
BrowserSync doesn't inject css changes

### ISSUE THREAD

**Issue by diegoviola1** [shakyShane/grunt-browser-sync#91]
Hello, I'm using Gruntfile.js provided by Foundation 5 as base start. BrowserSync "works", it show to me on top right "Connected to BrowserSync", but when I made a *.scss/css change, nothing happen on the browser.

This is my console log:

```
Running "browserSync:dev" (browserSync) task

Running "sass:dist" (sass) task
[BS] Proxying: http://mysite.dev
[BS] Now you can access your site through the following addresses:
[BS] Local URL: http://localhost:3000/app_dev.php/build
[BS] External URL: http://192.168.2.113:3000/app_dev.php/build
[BS] Watching files...

Running "watch" task
Waiting...
[BS] File changed: css/app.css
>> File "scss/app.scss" changed.
Running "sass:dist" (sass) task

Done, without errors.
Completed in 0.700s at Wed Jan 21 2015 10:11:42 GMT+0100 (CET) - Waiting...
[BS] File changed: css/app.css

```
Local URL and External URL works fine. BrowserSync reload not.
My Gruntfile.js: http://pastebin.com/NQkbgUG1

Package.json:
```
{
  "name": "foundation-libsass-template",
  "version": "0.0.1",
  "devDependencies": {
    "grunt": "~0.4.5",
    "grunt-browser-sync": "^1.5.3",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-sass": "~0.17.0",
    "node-sass": "~1.2.3"
  }
}
```
Thanks.

**Comment by shakyShane** [comment]
It was a bug, thanks for reporting it!

please run 

```shell
npm install grunt-browser-sync@1.9.1
```

Then clear you're browser cache & all will be fixed. :)

**Comment by diegoviola1** [comment]
Thanks for reply, but your solution did not solve my problem :(

It is normal that the console is not is not show up anything to indicate the browser will be updated? BrowserSync works, but whenever the css is compiled seems that it does't notice.
```
Done, without errors.
Completed in 0.660s at Wed Jan 21 2015 10:51:39 GMT+0100 (CET) - Waiting...
[BS] File changed: css/app.css
```

**Comment by shakyShane** [comment]
`[BS] File changed: css/app.css`

**Comment by diegoviola1** [comment]
I was thinking something like "Injecting CSS or Browser refresh" immediately after that event.

Anyway, I tried on another laptop with Ubuntu (before I was using an MacBook Pro), same problem with same gruntfile.js. Maybe with a proxy there are problems?

**Comment by benfrain** [comment]
Unsure if my problem is related.

- I'm running 1.9.1
- I'm using Chrome Version 40.0.2214.93 (64-bit) on a Mac
- I'm using a proxy (using 'grunt-contrib-connect' as the server) like this:

```
browserSync: {
	dev: {
		bsFiles: {
			src : [liveReloadWatchItems]
		},
		options: {
			proxy: "0.0.0.0:9001",
			watchTask: true
		}
	}
},
```

Making a change sees 'injected: styles.css' message at the top right of the browser, but doesn't actually inject the styles. I have to manually refresh to see the change.

If I switch the proxy off then injections work as expected (although I obviously can't then see anything on my external devices).

Is there anything else I have missed in the setup that would make the injections function over proxy?
