### ISSUE TITLE
Clarification: is the script necessary with proxy setup too?

### ISSUE THREAD

**Issue by benfrain** [shakyShane/grunt-browser-sync#92]
Could someone confirm whether the script is necessary when using proxy setup too?

I'm talking about this snippet that goes at the bottom of the HTML:

```
<script type='text/javascript' id="__bs_script__">//<![CDATA[
	    document.write("<script async src='//HOST:3000/browser-sync/browser-sync-client.1.9.1.js'><\/script>".replace(/HOST/g, location.hostname).replace(/PORT/g, location.port));
	//]]></script>
```

Reason I ask is that when you opt for the proxy based setup there is no message in the terminal providing the script (hence I didn't put it in). Should there be?

I had omitted it when setting up via proxy and I wonder if that's why I was getting the 'injected: styles.css' message but not actually getting a change in the browser?

**Comment by shakyShane** [comment]
no - the whole reason for the proxy is to auto-inject the script.

when running in proxy mode (without manually pasting the snippet), do you see "Connected to BrowserSync" in the browser?

**Comment by benfrain** [comment]
Yes, I do. Some more info:

Unsure if my problem is related.

- I'm running 1.9.1
- I'm using Chrome Version 40.0.2214.93 (64-bit) on a Mac
- I'm using a proxy (using 'grunt-contrib-connect' as the server) like this:

```
browserSync: {
	dev: {
		bsFiles: {
			src : [liveReloadWatchItems]
		},
		options: {
			proxy: "0.0.0.0:9001",
			watchTask: true
		}
	}
},
```

Making a change to CSS (via Sass) sees 'injected: styles.css' message at the top right of the browser, but doesn't actually inject the styles. I have to manually refresh to see the change.

If I switch the proxy off then injections work as expected (although I obviously can't then see anything on my external devices).

Is there anything else I have missed in the setup that would make the injections function over proxy?

**Comment by benfrain** [comment]
Anyone reading this in the future; the problem I had was not to do with browser sync. It was something particular to my project (a.k.a. 'error between keyboard and chair')
